model: "FastSpeech"
sample_rate: &sr 22050
# <PAD>, <BOS>, <EOS> will be added by the fastspeech.py script.
labels: &labels [' ', '!', '"', "'", '(', ')', ',', '-', '.', ':', ';', '?', 'A', 'B',
         'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
         'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', 'a', 'b',
         'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p',
         'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
n_fft: &n_fft 1024
n_mels: &n_mels 80
fmax: &fmax 8000
n_stride: &n_window_stride 256
pad_value: &pad_value -11.52

FastSpeechDataLayer:
    header: {collection_type: asr, collection_version: null,
             full_spec: nemo.collections.tts.FastSpeechDataLayer, nemo_core_version: 0.9.5}
    init_params:
        drop_last: false
        int_values: false
        labels: *labels
        load_audio: true
        max_duration: null
        min_duration: 0.1
        normalize_transcripts: false
        sample_rate: *sr
        trim_silence: false
        shuffle: true

AudioToMelSpectrogramPreprocessor:
    header: {full_spec: nemo.collections.asr.audio_preprocessing.AudioToMelSpectrogramPreprocessor,
             collection_type: asr, collection_version: null, nemo_core_version: 0.9.5}
    init_params:
        dither: 0.0
        features: *n_mels
        frame_splicing: 1
        highfreq: *fmax
        log: true
        log_zero_guard_type: clamp
        log_zero_guard_value: 1e-05
        lowfreq: 0
        mag_power: 1.0
        n_fft: *n_fft
        n_window_size: 1024
        n_window_stride: *n_window_stride
        normalize: null
        pad_to: 16
        pad_value: *pad_value
        preemph: null
        sample_rate: *sr
        stft_conv: true
        window: hann
        window_size: null
        window_stride: null

FastSpeech:
    header: {full_spec: nemo.collections.tts.FastSpeech,
             collection_type: asr, collection_version: null, nemo_core_version: 0.9.5}
    init_params:
        decoder_output_size: 384
        n_mels: *n_mels
        max_seq_len: 2048
        word_vec_dim: 384
        encoder_n_layer: 6
        encoder_head: 2
        encoder_conv1d_filter_size: 1536
        decoder_n_layer: 6
        decoder_head: 2
        decoder_conv1d_filter_size: 1536
        fft_conv1d_kernel: 3
        fft_conv1d_padding: 1
        encoder_output_size: 384
        duration_predictor_filter_size: 256
        duration_predictor_kernel_size: 3
        dropout: 0.1
        alpha: 1.0