model: "Jasper"
sample_rate: &sample_rate 16000
dropout: &drop 0.0
repeat:  &rep  1

labels: &labels [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]


AudioToTextDataLayer_train:
    header:
        full_spec: nemo.collections.asr.AudioToTextDataLayer
    init_params:
        sample_rate: *sample_rate
        labels: *labels
        batch_size: 48
        shuffle: true


AudioToTextDataLayer_eval:
    header:
        full_spec: nemo.collections.asr.AudioToTextDataLayer
    init_params:
        sample_rate: *sample_rate
        labels: *labels
        batch_size: 64
        shuffle: false


AudioToMelSpectrogramPreprocessor:
    header:
        full_spec: nemo.collections.asr.AudioToMelSpectrogramPreprocessor
    init_params:
        normalize: "per_feature"
        window_size: 0.02
        sample_rate: *sample_rate
        window_stride: 0.01
        window: "hann"
        features: &n_mels 64
        n_fft: 512
        frame_splicing: 1
        dither: 0.00001
        stft_conv: true

JasperEncoder:
    header:
        full_spec: nemo.collections.asr.JasperEncoder
    init_params:
        feat_in: *n_mels
        activation: "relu"

        jasper:
            -   filters: 128
                repeat: 1
                kernel: [11]
                stride: [1]
                dilation: [1]
                dropout: *drop
                residual: true

            -   filters: 256
                repeat: *rep
                kernel: [13]
                stride: [1]
                dilation: [1]
                dropout: *drop
                residual: true

            -   filters: 256
                repeat: *rep
                kernel: [15]
                stride: [1]
                dilation: [1]
                dropout: *drop
                residual: true

            -   filters: 256
                repeat: *rep
                kernel: [17]
                stride: [1]
                dilation: [1]
                dropout: *drop
                residual: true

            -   filters: 256
                repeat: *rep
                kernel: [19]
                stride: [1]
                dilation: [1]
                dropout: *drop
                residual: true

            -   filters: 256
                repeat: 1
                kernel: [21]
                stride: [1]
                dilation: [1]
                dropout: 0.0
                residual: false

            -   filters: &enc_feat_out 1024
                repeat: 1
                kernel: [1]
                stride: [1]
                dilation: [1]
                dropout: 0.0
                residual: false

JasperDecoderForCTC:
    header:
        full_spec: nemo.collections.asr.JasperDecoderForCTC
    init_params:
        feat_in: *enc_feat_out
