model: "Jasper"

# Sample rate is passed to many NMs, so it is defined at the top level
sample_rate: 16000

AudioToTextDataLayer:
    int_values: false
    min_duration: 0.0
    max_duration: 16.7
    trim_silence: true
    load_audio: true
    drop_last: false
    normalize_transcripts: true

    train:
        shuffle: true

    eval:
        shuffle: false
        max_duration: null

AudioToMelSpectrogramPreprocessor:
    window_size: 0.02
    window_stride: 0.01
    window: "hann"
    normalize: "per_feature"
    preemph: 0.97
    n_fft: 512
    features: 64
    lowfreq: 0
    highfreq: null
    dither: 0.00001
    pad_to: 16
    frame_splicing: 1
    stft_conv: true

MultiplyBatch:

SpectrogramAugmentation:

JasperEncoder:
    activation: "relu"
    conv_mask: true

    jasper:
        -   filters: 256
            repeat: 1
            kernel: [11]
            stride: [2]
            dilation: [1]
            dropout: 0.2
            residual: false

        -   filters: 256
            repeat: 4
            kernel: [11]
            stride: [1]
            dilation: [1]
            dropout: 0.2
            residual: true

        -   filters: 256
            repeat: 4
            kernel: [11]
            stride: [1]
            dilation: [1]
            dropout: 0.2
            residual: true

        -   filters: 384
            repeat: 4
            kernel: [13]
            stride: [1]
            dilation: [1]
            dropout: 0.2
            residual: true

        -   filters: 384
            repeat: 4
            kernel: [13]
            stride: [1]
            dilation: [1]
            dropout: 0.2
            residual: true

        -   filters: 512
            repeat: 4
            kernel: [17]
            stride: [1]
            dilation: [1]
            dropout: 0.2
            residual: true

        -   filters: 512
            repeat: 4
            kernel: [17]
            stride: [1]
            dilation: [1]
            dropout: 0.2
            residual: true

        -   filters: 640
            repeat: 4
            kernel: [21]
            stride: [1]
            dilation: [1]
            dropout: 0.3
            residual: true

        -   filters: 640
            repeat: 4
            kernel: [21]
            stride: [1]
            dilation: [1]
            dropout: 0.3
            residual: true

        -   filters: 768
            repeat: 4
            kernel: [25]
            stride: [1]
            dilation: [1]
            dropout: 0.3
            residual: true

        -   filters: 768
            repeat: 4
            kernel: [25]
            stride: [1]
            dilation: [1]
            dropout: 0.3
            residual: true

        -   filters: 896
            repeat: 1
            kernel: [29]
            stride: [1]
            dilation: [2]
            dropout: 0.4
            residual: false

        -   filters: 1024
            repeat: 1
            kernel: [1]
            stride: [1]
            dilation: [1]
            dropout: 0.4
            residual: false

labels: [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]
