model: "QuartzNet-AN4"
sample_rate: 16000
dropout: &drop 0.0
repeat:  &rep  1

#optimization:
#    batch_size: 256
#    optimizer: "novograd"
#    smoothing_coef: 0.0
#    warmup_epochs: 0
#    params:
#        num_epochs: 500
#        lr: 0.02
#        weight_decay: 0.005

AudioToTextDataLayer:
    train:
        trim_silence: &ts true
        normalize_transcripts: &nt true
        shuffle: true
        max_duration: 16.7
        drop_last: true

    eval:
        trim_silence: *ts
        normalize_transcripts: *nt
        shuffle: false
        max_duration: null
        drop_last: false

AudioToMelSpectrogramPreprocessor:
    normalize: "per_feature"
    window_size: 0.02
    window_stride: 0.01
    window: "hann"
    features: 64
    n_fft: 512
    dither: 0.00001
    pad_to: 16
    stft_conv: true


JasperEncoder:
    activation: "relu"
    jasper:
        -   filters: 128
            repeat: 1
            kernel: [11]
            stride: [1]
            dilation: [1]
            dropout: *drop
            residual: true
            separable: true

        -   filters: 256
            repeat: *rep
            kernel: [13]
            stride: [1]
            dilation: [1]
            dropout: *drop
            residual: true
            separable: true

        -   filters: 256
            repeat: *rep
            kernel: [15]
            stride: [1]
            dilation: [1]
            dropout: *drop
            residual: true
            separable: true

        -   filters: 256
            repeat: *rep
            kernel: [17]
            stride: [1]
            dilation: [1]
            dropout: *drop
            residual: true
            separable: true

        -   filters: 256
            repeat: *rep
            kernel: [19]
            stride: [1]
            dilation: [1]
            dropout: *drop
            residual: true
            separable: true


        -   filters: 256
            repeat: 1
            kernel: [21]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false
            separable: true

        -   filters: 1024
            repeat: 1
            kernel: [1]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false

labels: [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]
